In [1]:
import numpy as np

In [4]:
L=np.arange(1,11)

In [5]:
L

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
L=np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
L

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
L.shape

(10,)

In [12]:
L[:5]

array([1, 2, 3, 4, 5])

In [13]:
L[5:]

array([ 6,  7,  8,  9, 10])

In [14]:
L[5:7]

array([6, 7])

In [15]:
L[::2]

array([1, 3, 5, 7, 9])

In [16]:
L[1::2]

array([ 2,  4,  6,  8, 10])

In [17]:
L[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
L

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
M=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
           ])

In [20]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
M[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
M[:2,:2]

array([[1, 2],
       [4, 5]])

In [23]:
M[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [24]:
M[1:,:2]

array([[4, 5],
       [7, 8]])

In [25]:
M[:1,:3]

array([[1, 2, 3]])

In [26]:
M[:,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
M[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [29]:
M[0][0]

1

In [30]:
M[0][1]

2

In [31]:
M[0][2]

3

In [32]:
M1=M[:2,:2]

In [33]:
M1

array([[1, 2],
       [4, 5]])

In [34]:
M1[0][0]=2

In [35]:
M1

array([[2, 2],
       [4, 5]])

In [36]:
M

array([[2, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
M2=M.copy()

In [38]:
M2

array([[2, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
M2[0][0]=1

In [40]:
M2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
M

array([[2, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
B=np.arange(1,10).reshape(3,3)

In [44]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
r=np.array([1,2,3])

In [46]:
r.reshape(1,3)

array([[1, 2, 3]])

In [53]:
r[np.newaxis,:]

array([[1, 2, 3]])

In [49]:
c=np.array([1,2,3])

In [50]:
c.reshape(3,1)

array([[1],
       [2],
       [3]])

In [52]:
c[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [56]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [59]:
a=np.array([[1,2,3],
          [4,5,6]])
b=np.array([[7,8,9],
           [10,11,12]])
np.concatenate([a,b])


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
np.concatenate([a,b],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [67]:
a=np.array([[1,2,3],
          [4,5,6]])
b=np.array([7,8,9])
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
a=np.array([[1,2,3],
          [4,5,6]])
b=np.array([[7],
          [8]])
np.hstack([a,b])

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [90]:
L=[1,2,3,4,5,6]
a,b,c=np.split(L,[3,5])
a,b,c

(array([1, 2, 3]), array([4, 5]), array([6]))

In [94]:
L=np.arange(1,6)
L

array([1, 2, 3, 4, 5])

In [95]:
L+5

array([ 6,  7,  8,  9, 10])

In [97]:
L-5

array([-4, -3, -2, -1,  0])

In [98]:
L*5

array([ 5, 10, 15, 20, 25])

In [99]:
L/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [100]:
L//5

array([0, 0, 0, 0, 1], dtype=int32)

In [101]:
L%5

array([1, 2, 3, 4, 0], dtype=int32)

In [102]:
-L

array([-1, -2, -3, -4, -5])

In [103]:
L**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [108]:
np.add(1,2)

3

In [109]:
np.subtract(2,1)

1

In [110]:
np.negative(1)

-1

In [111]:
np.multiply(1,2)

2

In [112]:
np.divide(2,1)

2.0

In [113]:
np.floor_divide(2,1)

2

In [114]:
np.power(2,3)

8

In [116]:
np.mod(4,3)

1

In [118]:
L=np.array([-1,2,-3])
abs(L)

array([1, 2, 3])

In [120]:
t = np.linspace(0, np.pi, 3)

In [122]:
np.sin(t)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [123]:
np.cos(t)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [125]:
np.tan(t)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [130]:
np.arcsin(1)

1.5707963267948966

In [131]:
np.arccos(1)

0.0

In [132]:
np.arctan(1)

0.7853981633974483

In [136]:
np.power(2,2)

4

In [138]:
np.exp2(2)

4.0

In [139]:
np.log(1)

0.0

In [140]:
np.log2(1)

0.0

In [142]:
np.log10(1)

0.0

In [144]:
L=np.random.random(100)
L

array([0.77576947, 0.71196953, 0.27873473, 0.60062819, 0.02519481,
       0.30787259, 0.46734454, 0.38823585, 0.9829707 , 0.64701586,
       0.22910627, 0.31136303, 0.2017195 , 0.71293287, 0.17793317,
       0.81402536, 0.92308788, 0.46843081, 0.36325409, 0.34359708,
       0.29107222, 0.32741779, 0.18880265, 0.97319631, 0.18338469,
       0.824005  , 0.93106578, 0.92355681, 0.63203   , 0.44491817,
       0.54286868, 0.16265556, 0.46497979, 0.1184917 , 0.27037449,
       0.46330151, 0.39722079, 0.34142026, 0.46961562, 0.09164441,
       0.14311086, 0.10155594, 0.20785865, 0.56541938, 0.35086278,
       0.73957035, 0.0667364 , 0.71797741, 0.93143564, 0.10934233,
       0.70256332, 0.0599765 , 0.01014045, 0.65426249, 0.07927538,
       0.99509365, 0.4545593 , 0.7556889 , 0.27767018, 0.76459326,
       0.3924541 , 0.97560786, 0.73105796, 0.26543282, 0.95321978,
       0.23457616, 0.5008212 , 0.85524438, 0.01181197, 0.4292634 ,
       0.96744624, 0.67318661, 0.96043468, 0.89102387, 0.10545

In [145]:
sum(L)

47.95505260139287

In [146]:
L.sum()

47.95505260139287

In [147]:
L.min()

0.010140453632977664

In [148]:
L.max()

0.9950936483252548

In [152]:
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]
a,b

(array([0, 1, 2]),
 array([[0],
        [1],
        [2]]))

In [153]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [158]:
L=np.random.randint(10,size=10)
L

array([3, 2, 5, 8, 6, 6, 0, 4, 5, 1])

In [159]:
[L[1],L[5],L[8]]

[2, 6, 5]

In [160]:
i=[1,2,3]
L[i]

array([2, 5, 8])

In [161]:
i=np.array([[1,2,3],
           [4,5,6]])
L[i]

array([[2, 5, 8],
       [6, 6, 0]])

In [162]:
M=np.array([[1,2,3],
           [4,5,6],
            [7,8,9]])
M[2,[2,0,1]]

array([9, 7, 8])

In [165]:
i=[1,2,3]
L[i]=1
L

array([3, 1, 1, 1, 6, 6, 0, 4, 5, 1])

In [186]:
rand=np.random.RandomState(42)
X=rand.randint(0,20,(4,4))
X

array([[ 6, 19, 14, 10],
       [ 7,  6, 18, 10],
       [10,  3,  7,  2],
       [ 1, 11,  5,  1]])

In [187]:
X.sort(axis=0)
X

array([[ 1,  3,  5,  1],
       [ 6,  6,  7,  2],
       [ 7, 11, 14, 10],
       [10, 19, 18, 10]])

In [188]:
X.sort(axis=1)
X

array([[ 1,  1,  3,  5],
       [ 2,  6,  6,  7],
       [ 7, 10, 11, 14],
       [10, 10, 18, 19]])

In [189]:
X.partition(2,axis=0)
X

array([[ 1,  1,  3,  5],
       [ 2,  6,  6,  7],
       [ 7, 10, 11, 14],
       [10, 10, 18, 19]])

In [190]:
X.partition(2,axis=1)
X

array([[ 1,  1,  3,  5],
       [ 2,  6,  6,  7],
       [ 7, 10, 11, 14],
       [10, 10, 18, 19]])